name = "openai-cf"                # todo
main = "index.js"
compatibility_date = "2024-04-05"
# compatibility_flags = [ "transformstream_enable_standard_constructor","streams_enable_constructors"]

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

# replace this with your own
[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "ai"
database_id = "9410ebff-8ece-48e6-b0d7-54540625ed54"

[vars]
ACCESS_TOKEN = "sk-123123123123123"
